<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Website Development,Web Application Development,Mobile Application Development</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<meta name="author" content="http://webthemez.com" />
 
<link href="css/bootstrap.min.css" rel="stylesheet" />
<link href="css/fancybox/jquery.fancybox.css" rel="stylesheet">
<link href="css/jcarousel.css" rel="stylesheet" />
<link href="css/flexslider.css" rel="stylesheet" />
<link href="css/style.css" rel="stylesheet" />
 
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>
<div id="wrapper">
	<?php include('top.php'); ?>
<!-- end header -->
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="pageTitle">About Us</h2>
			</div>
		</div>
	</div>
	</section>
	<section id="content">
		<div class="container content">		
        <!-- Service Blcoks -->
			
						<div class="row"> 
							<div class="col-md-12">
								<div class="about-logo">
									<p align=justify><font face="Calibri" size=3 color=black><b>Incredible Tech Solutions </b> is professional Software development company,
				        	we offer a wide range of services to reach your targeted audience and share your valuable information focusing on retaining your
				         	customers. We have the expertise to make your communication and transactions on the internet effective. We ensure this through 
				         	appropriate content and suitable internet tools, sufficient enough to reach far and wide markets. 
							Incredible Technology Solutions services leverage
				          	deep domain expertise in the Industry, technical expertise in leading Core Manufacturing and Design Tool technologies and a 
				          	cost-effective global solutions delivery model. 
				       		The services are provided under the aegis of our communications and e-business practices..</font>
				       		</p>
				       		<P align=justify><font face="Calibri" size=3 color=black>Incredible delivers software solutions, many of 
                              them based on the patented technologies of our 
                              clients. Our clients success stories are a 
                              reflection of our client-centric approach. This 
                              has in turn facilitated the growth and success of 
                              our company.</font></P>
                               <font face="Calibri" size=3 color=black>
                              <P align=justify><STRONG><b>Our Vision : </b></STRONG><BR>
                             
                              Our vision is to 
                              achieve and maintain an industry leading position 
                              as providers of world-class software solutions. We 
                              continuously strive to expand the sphere of our 
                              expertise and the value of our services. We pride 
                              ourselves on providing innovative solutions 
                              tailored to suit the requirements of our clients 
                              engineered to the highest standards of quality.</font></P>
                              <P align=justify><font face="Calibri" size=3 color=black>We are probably among one of the few companies 
                              in the world who don't have a marketing department 
                              to sell our services. The horizon of happy and 
                              satisfied customers has been expanding due to the 
                              publicity generated by our existing clients who 
                              have referred us to their associates. This has 
                              ensured the company's exponential growth.</font></P>
                              <font face="Calibri" size=3 color=black>
                              <P align=justify><STRONG><b>Our People : </b><BR></A></STRONG>
                              Our pool of handpicked and talented software engineers and 
                              consultants thrive on technical challenges. Our 
                              informal, team-oriented, technically demanding 
                              operational structure has helped us in maintaining 
                              the highest quality of software professionals. We 
                              work with the latest technologies in developing 
                              software application tools, delivering solutions 
                              and services.</font></P>
                              <P align=justify><font face="Calibri" size=3 color=black>In order to stay on top of the competition, we 
                              hire, train and motivate good talent. This allows 
                              us to have a professional team of software 
                              engineers, designers and artists working on all 
                              our projects. They have the skills, experience, 
                              high standards of technical knowledge and are very 
                              well motivated to achieve the desired output.</font></P>
                              <P align=justify><font face="Calibri" size=3 color=black>We understand how important it is to create an 
                              environment that is motivating, exciting and 
                              beneficial to all employees. Our informal and 
                              relaxed working environment encourages interaction 
                              between employees, discussions, celebration of 
                              special occasions and outings that are thoroughly 
                              enjoyed by all the employees.</font></P>
                              <P align=justify><font face="Calibri" size=3 color=black>In the software industry manpower turnover 
                              levels are very high, but the motivating working 
                              environment that we as a company believe in helps 
                              us in building a bond with our people and we are 
                              able to keep manpower turnover at its minimum.</font></P>
                              <font face="Calibri" size=3 color=black>
                              <P align=justify><STRONG><BR><b>Our Work culture</b></STRONG><BR>
                              
                              At Incredible, the work culture is based on a strong 
                              foundation of positive thinking and mutual 
                              co-operation. Positive thinking that is developed 
                              through positive emotions, positive analyzing and 
                              realization is the key to our success. Also, an 
                              environment of mutual co-operation and 
                              understanding focuses on the importance and growth 
                              of every individual which in turn leads to the 
                              overall growth of the company. </font></P>
								</div>  
							</div>
						</div>
						 
	
     

        
    </div>
    </section>
<?php include('bottom.php'); ?>
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.fancybox.pack.js"></script>
<script src="js/jquery.fancybox-media.js"></script>  
<script src="js/jquery.flexslider.js"></script>
<script src="js/animate.js"></script>
<!-- Vendor Scripts -->
<script src="js/modernizr.custom.js"></script>
<script src="js/jquery.isotope.min.js"></script>
<script src="js/jquery.magnific-popup.min.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>
</body>
</html>